- ros_topic_name: clock
  gz_topic_name: clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
  qos_profile: CLOCK
- ros_topic_name: meter_dataset/camera/camera_info
  gz_topic_name: meter_dataset/camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: meter_dataset/joint_states
  gz_topic_name: meter_dataset/joint_states
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
- ros_topic_name: meter_dataset/pressure/needle_cmd
  gz_topic_name: /model/synthetic_meter_pressure/joint/needle_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: meter_dataset/oil/needle_cmd
  gz_topic_name: /model/synthetic_meter_oil/joint/needle_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
